#!/bin/sh

echo initramfs loaded!

rc-update add add-extra sysinit

rc-update add mdevd sysinit
rc-update add mdevd-init sysinit
rc-update add hwdrivers sysinit

rc-update add devfs sysinit
rc-update add dmesg sysinit

rc-update add hwclock boot
rc-update add modules boot
rc-update add sysctl boot
rc-update add hostname boot
rc-update add bootmisc boot
rc-update add syslog boot

rc-update add mount-ro shutdown
rc-update add killprocs shutdown
rc-update add savecache shutdown

rc-update add ntpd default

bbsuid --install

echo starting busybox init
exec /sbin/init

