# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.5.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/celestials-closet: 05707ca2ae5a2d85b0a883375781b67f66026cbfe61b6fea42ba02fa12674968
    io.kubernetes.cri-o.SandboxID/cobalt: 05707ca2ae5a2d85b0a883375781b67f66026cbfe61b6fea42ba02fa12674968
  creationTimestamp: "2025-06-25T07:49:08Z"
  labels:
    app: services
  name: services
spec:
  shareProcessNamespace: true
  containers:
  - image: ghcr.io/celestialcrafter/celestials-closet:latest
    name: celestials-closet
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 9000
      hostPort: 9000
    volumeMounts:
    - mountPath: /data
      name: celestials-closet-pvc
  - args:
    - node
    - src/cobalt
    env:
    - name: RATELIMIT_MAX
      value: "100000"
    - name: SESSION_RATELIMIT_WINDOW
      value: "0"
    - name: SESSION_RATELIMIT_MAX
      value: "100000"
    - name: TUNNEL_RATELIMIT_WINDOW
      value: "0"
    - name: API_URL
      value: http://localhost:9000
    - name: TUNNEL_LIFESPAN
      value: "300"
    - name: DURATION_LIMIT
      value: "360000"
    - name: TUNNEL_RATELIMIT_MAX
      value: "100000"
    - name: RATELIMIT_WINDOW
      value: "0"
    image: ghcr.io/imputnet/cobalt:latest
    name: cobalt
    securityContext: {}
  volumes:
  - name: celestials-closet-pvc
    persistentVolumeClaim:
      claimName: celestials-closet

