#!/bin/sh
set -euo pipefail

echo installing extra

mount -t devtmpfs none /dev
mount /mnt-deploy

{
  store=$(zmap --target-port 7435 192.168.0.0/24 | head -n1)
  hash=$(wget $store/extra-current.tar.zst.sha256 -O -)

  if [ "$hash" != $(cat /mnt-deploy/sha256) ]; then
    echo "store hash differs, updating deployment"

    wget $store/extra-current.tar.zst -P /tmp

    rm -rf /mnt-deploy/*
    tar -xf /tmp/extra-current.tar.zst -C /mnt-deploy
    echo $hash > /mnt-deploy/sha256
  fi
} || echo "could not update deployment"

cp -r /mnt-deploy/extra/* /

umount /mnt-deploy
umount /dev

/post-init

