#!/bin/sh
echo installing extra

mount -t devtmpfs none /dev
mount /mnt-deploy

cp -r /mnt-deploy/extra/files/* /
CACHE=/mnt-deploy/extra/cache
apk add --cache-dir $CACHE --no-network $(cat $CACHE/installed)

umount /mnt-deploy
umount /dev

/post-init

