#!/bin/sh
echo running extra post-init

apk add --no-network $(cat /etc/apk/cache/installed)

rc-update add hwdrivers sysinit

rc-update add devfs sysinit
rc-update add dmesg sysinit
rc-update add mdevd sysinit
rc-update add mdevd-init sysinit

rc-update add hwclock boot
rc-update add modules boot
rc-update add sysctl boot
rc-update add hostname boot
rc-update add bootmisc boot
rc-update add syslog boot
rc-update add cgroups boot
rc-update add tailscale boot

rc-update add sshd default
rc-update add ntpd default
rc-update add services default

rc-update add mount-ro shutdown
rc-update add killprocs shutdown
rc-update add savecache shutdown

bbsuid --install

echo running busybox init
exec /sbin/init
